columns:
  - person_age: int
  - person_income: int
  - person_home_ownership: category
  - person_emp_length: int
  - loan_intent: category
  - loan_grade: category
  - loan_amnt: int
  - loan_int_rate: int
  - loan_status: int
  - loan_percent_income: int
  - cb_person_default_on_file: category
  - cb_person_cred_hist_length: int

numerical_columns:
  - person_age 
  - person_income 
  - person_emp_length
  - loan_amnt
  - loan_int_rate
  - loan_status
  - loan_percent_income
  - cb_person_cred_hist_length

categorical_columns: 
  - person_home_ownership
  - loan_intent
  - loan_grade
  - cb_person_default_on_file

imputation:
  technique: KNNImputer
  neighbors: 5
  columns:
    - person_emp_length
    - loan_int_rate


outlier_rules:
  - column: person_age
    max: 100
  - column: person_emp_length
    max: 100

# for data transformation
num_features:
  - person_age 
  - person_income 
  - person_emp_length
  - loan_amnt
  - loan_int_rate
  - loan_percent_income
  - cb_person_cred_hist_length

or_columns:
  - loan_grade

oh_columns:
 - person_home_ownership
 - loan_intent 
